### ISSUE TITLE
refactor: move cost of carry logic to analytics sdk

### ISSUE THREAD

**Issue by janndriessen** [IndexCoop/index-app#1332]
* the AnalyticsSDK would be a great place as it's easy to write tests there
* and even better, this way we could remove `JsonRpcProvider` from the app (as this is the last place where it's used now)

**Comment by janndriessen** [comment]
Let me know what you think? @0xonramp

**Comment by 0xonramp** [comment]
@janndriessen I like the idea a lot, because we could move the other aave-specific dependencies used in calculating it out of the frontend

I tweaked the logic on friday and think it's close to being right, but will need to cross-check it with another source this week

**Comment by 0xonramp** [comment]
Closing - we'll be removing the logic entirely and relying on Dune for it.
