### ISSUE TITLE
Unable to perform a swap from BED to ETH

### ISSUE THREAD

**Issue by mayurjobanputra** [IndexCoop/index-app#1361]
**Describe the bug**
I have ~4 BED tokens. I'm trying to swap back to ETH. But I'm unable to get the ETH field to populate and I can't click Approve either. See discussion ongoing at https://www.reddit.com/r/INDEXcoop/comments/1di4n3i/unable_to_sellswap_bed_help/ for more information about the issue.

**To Reproduce**

1. Load up BED tokens in Brave. 
2. Use Brave Wallet to connect to Ledger.
3. Try going to [index app
](https://app.indexcoop.com/swap/bed/gusd) to swap.

**Expected behavior**
Ability to see ETH value populated and/or click Approve to complete the transfer

**Screenshot:**
see below...
![image](https://github.com/IndexCoop/index-app/assets/6332663/7d23211f-b8fe-46e2-a0cc-e1e4901a95c8)

**Desktop (please complete the following information):**

- OS: Mac OS X: 14.5.0
- Browser Brave Browser and Brave Wallet
- Version: 126.1.67.116

**Comment by janndriessen** [comment]
For redeeming of BED please use https://app.indexcoop.com/legacy from now on.
